#!/bin/bash

set -e

source $SRCROOT/integration/common

trap exit_handler EXIT

heading 'Setup...'

echo 'logging in..'
# we do this at run-time instead of build time
# to eliminate the risk of copying over a stale nulink binary
# if we had instead copied over the binary from the built nulink
# base image
# we could also try mounting a volume instead, or using docker-exec
docker cp nulink-node:/usr/local/bin/nulink /usr/local/bin/nulink
nulink admin login --file /run/secrets/apicredentials
launch_nulink
deploy_contracts

heading 'Running tests...'
cd $SRCROOT/integration

./runlog_test
./ethlog_test
deploy_v05_contracts
./service_agreement_test

deploy_v06_contracts
./flux_monitor_test

title 'End to end tests.'

yarn workspace @nulink/integration test:cypress
title 'All tests passed.'
