#!/bin/bash

set -ex

#
# Pushes smartercontractkits/nulink:circleci to relevant location based on passed args:
# push_nulink <branch> <gittag>
# ie:
# push_nulink master 0.6.9
# push_nulink develop
# push_nulink release/0.6.9
#
# Ignores anything not matching above.
# Key assumption: local version of smartercontractkits/nulink:circleci is the image
# to work with.
#

if [ -z "$DOCKERHUB_PASS" ]
then
  echo "Skipping dockerhub uploads because the necessary credentials are not present"
  exit 0
fi

circle_branch="$1"
circle_tag="$2"

PROJECT_ROOT=`git rev-parse --show-toplevel`
pushd $PROJECT_ROOT >/dev/null

tag_and_push() {
  # ie: docker tag and push smartercontractkits/nulink:0.9.1, since DOCKER_TAG=0.9.1
  export DOCKER_TAG=$1
  (set -x; docker tag smartercontractkits/nulink:circleci smartercontractkits/nulink:${DOCKER_TAG})
  make dockerpush
}

branch_tag=`tools/ci/branch2tag ${circle_branch}` # ie: develop, latest, candidate-*, etc.
version_tag=`tools/ci/gittag2dockertag ${circle_tag}` # aka GIT_TAG. v0.9.1 -> 0.9.1

# version tag takes precedence.
if [ -n "${version_tag}" ]; then
  tag_and_push "$version_tag"
  # if version tag, also push latest.
  # ie: after pushing smartercontractkits/nulink:0.6.9, also update smartercontractkits/nulink:latest
  tag_and_push latest
else
  tag_and_push "$branch_tag"
fi
