#!/bin/bash

set -e

yarn workspace @nulink/box run lint
yarn setup:contracts

# These should be merged into a global test command
yarn workspace @nulink/contracts test
yarn workspace @nulink/box test
